<a href="https://colab.research.google.com/github/heenakouser1/Gen-ai-batch-2024/blob/main/Numpy_assignment_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Theory questions

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations

NumPy is a fundamental library in Python for scientific computing. It offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently.

NumPy (Numerical Python) is an open source Python library that has a wide range of inbuilt functions.

Advantage of Numpy :NumPy is ideal for handling large amounts of homogeneous (same-type) data, offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.



2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other

In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [6]:
np.mean(a)   # mean can be used when we are working on statictics or EDA process

2.5

In [7]:
np.average(a) # np.avearge can be used during general compuatation

2.5

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays

In [8]:
a = np.array([[3,4],[4,5]])
a

array([[3, 4],
       [4, 5]])

In [15]:
np.flip(a,axis = 0)   # rowise

array([[4, 5],
       [3, 4]])

In [16]:
np.flip(a,axis=1)   # column

array([[4, 3],
       [5, 4]])

In [17]:
b = np.array([1,2,4])
b

array([1, 2, 4])

In [18]:
np.flip(b,axis =0)# row

array([4, 2, 1])

In [19]:
np.flip(b,axis=1)  # column

AxisError: axis 1 is out of bounds for array of dimension 1

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performanc

In [29]:
# In NUmpy the elements are stored in form of array, which are homogenous in nature, when the input given is also off different datatypes, even then
# numpy convert them into a same data type, doing this the memory allocated to this array is continous. This make the access faster

c = np.array([1,2,4,5])
c

array([1, 2, 4, 5])

In [30]:
c.dtype    #  using dtype we can know the datatype of array elements

dtype('int64')

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists

In [ ]:
# ndarray are n-diemensional array contains the homogenous data. as they have same data type they are easy to access and faster
# these array are built in numpy. As numpy are built in c lang, so it makes then faster for computation

# list are heterogenous data, where elements in list might be stored in different memory location. making it difficult for faster access

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

In [42]:
# numpy    computing time for numpy is very less compare to lists, and also the built in module for sqrt is readily avaliable in numpy
import time

print("numpy")
start = time.time()
a = np.array([12,3,4])
np.sqrt(a)
end = time.time()
print(end-start)

numpy
0.00020241737365722656


In [44]:
# lists
import math
import time

print("list")
start = time.time()
l = [12,3,4]
for i in l:
  math.sqrt(i)
end = time.time()
print(end-start)

list
0.00021696090698242188


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output

If you have two matrices, good to go with just hstack and vstack:

If you're stacking a matrice and a vector, hstack becomes tricky to use, so column_stack is a better option

In [49]:
a = np.array([[1,2,4],[4,4,4]])
a

array([[1, 2, 4],
       [4, 4, 4]])

In [51]:
np.vstack(a)

array([[1, 2, 4],
       [4, 4, 4]])

In [52]:
np.hstack(a)

array([1, 2, 4, 4, 4, 4])

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

As fliplr and flipud works on >2d array using below examples

In [58]:
d = np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.fliplr(d)    # it flip or reverse elements in axis = 1

array([[3, 2, 1],
       [6, 5, 4]])

In [60]:
np.flipud(d)    # it flip or reverse elements in axis =0

array([[4, 5, 6],
       [1, 2, 3]])

In [65]:
e = np.array([[[1,2,3],[2,3,4],[11,222,32]]])
e

array([[[  1,   2,   3],
        [  2,   3,   4],
        [ 11, 222,  32]]])

In [66]:
np.fliplr(e)      # here flip happend in axis = 0

array([[[ 11, 222,  32],
        [  2,   3,   4],
        [  1,   2,   3]]])

In [67]:
np.flipud(e)  # it remains sames

array([[[  1,   2,   3],
        [  2,   3,   4],
        [ 11, 222,  32]]])

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits

The array_split() function from NumPy is used to split an array into sub-arrays. When the split is uneven (i.e., the number of elements in the array cannot be evenly divided by the number of splits), array_split() ensures that the sub-arrays are as balanced as possible by distributing the remainder across the first few sub-arrays.

In [71]:
f = np.arange(10)
f1 = np.array_split(f,5)
f1

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [76]:
f2 = np.array_split(f,7)
f2

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6]),
 array([7]),
 array([8]),
 array([9])]

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations

Vectorization and broadcasting are two core concepts in NumPy that significantly contribute to its efficiency and ease of use for array operations. They eliminate the need for explicit loops and allow computations to be expressed in a concise and computationally efficient manner.

In [84]:
h = np.zeros((2,2))
h

array([[0., 0.],
       [0., 0.]])

In [85]:
h + 5    # broadcasting will allow the change of all elements of array

array([[5., 5.],
       [5., 5.]])

In [86]:
h1 = np.array([[1,2],[3,4]])
h1

array([[1, 2],
       [3, 4]])

In [87]:
h + h1    # vectorization will allow the elements addition faster , avoiding the loops

array([[1., 2.],
       [3., 4.]])

## PRACTICAL Questions

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [88]:
import random
a = np.random.randint(1,100,(3,3))
a

array([[26, 63, 52],
       [81, 99, 77],
       [87, 86, 93]])

In [89]:
np.roll(a,-1,axis=0)

array([[81, 99, 77],
       [87, 86, 93],
       [26, 63, 52]])

In [90]:
np.roll(a,-1,axis=1)

array([[63, 52, 26],
       [99, 77, 81],
       [86, 93, 87]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [92]:
b = np.arange(10)
b1 = np.array(b)
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
b1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
b1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [95]:
a = np.random.rand(4,4)
a

array([[0.55647235, 0.11005462, 0.82475511, 0.34604093],
       [0.48860446, 0.50961233, 0.75683582, 0.7701639 ],
       [0.73934035, 0.59030969, 0.35902458, 0.96588365],
       [0.32507104, 0.96248142, 0.64387356, 0.93565494]])

In [103]:
a1 = np.pad(a,pad_width=1,mode='constant',constant_values=0)
a1

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.55647235, 0.11005462, 0.82475511, 0.34604093,
        0.        ],
       [0.        , 0.48860446, 0.50961233, 0.75683582, 0.7701639 ,
        0.        ],
       [0.        , 0.73934035, 0.59030969, 0.35902458, 0.96588365,
        0.        ],
       [0.        , 0.32507104, 0.96248142, 0.64387356, 0.93565494,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [104]:
a1.shape

(6, 6)

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [105]:
a = np.arange(10,60,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element

In [106]:
a = np.array(['python', 'numpy', 'pandas'])
a

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [107]:
np.char.upper(a)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [108]:
np.char.lower(a)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [109]:
np.char.title(a)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [110]:
a = np.array(['python', 'numpy', 'pandas'])
a

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [130]:
new = np.array([' '.join(i) for i in a])
print(new)

['p y t h o n' 'n u m p y' 'p a n d a s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and divisio

In [131]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [132]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [133]:
a + b  # addition

array([[ 6,  8],
       [10, 12]])

In [134]:
a -b# substraction

array([[-4, -4],
       [-4, -4]])

In [135]:
a * b   # multiplication

array([[ 5, 12],
       [21, 32]])

In [136]:
a /b   # divsion

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [140]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [141]:
a[a==1]

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [148]:
a = np.random.randint(0,1000,size = 100)
a

array([601, 159, 807, 460, 962, 407, 701, 236, 145, 133, 772, 383, 638,
       149,  87, 578,  83, 566, 947,   5, 505, 286, 151, 738, 706,  47,
        33, 330, 752,  41, 302, 777, 572, 438, 302, 973, 526, 215, 540,
       170, 853, 674, 253, 185,  91, 436, 377, 725, 187, 600, 587, 298,
       131, 102,  13, 727, 239, 721, 709, 462, 594, 123, 627, 885, 688,
       992, 719, 860, 919, 879, 127, 669, 539, 871, 802, 897, 682, 915,
       344, 135, 558, 635, 158, 827,  44, 882,  97, 829, 732, 420, 686,
       591, 241, 725, 828, 248, 486, 174, 632, 492])

In [157]:
for i in a:
  if i > 1:
    for j in range(2,i):
      if i%j == 0:
        break
    else:
      print(i,end = ',')

601,701,383,149,83,947,5,151,47,41,853,587,131,13,727,239,709,719,919,127,827,97,829,241,

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages

In [160]:
a = np.random.randint(10,100,size = 30)
a

array([74, 37, 30, 30, 16, 88, 21, 42, 91, 78, 21, 98, 52, 97, 39, 64, 64,
       19, 80, 91, 81, 15, 39, 37, 72, 45, 94, 40, 55, 85])

In [163]:
i = 0
while i < len(a):
  print(a[i:i+7].mean())
  i += 7

42.285714285714285
68.42857142857143
62.57142857142857
48.857142857142854
70.0
